// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/v1/positions.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PositionService_PositionCreate_FullMethodName = "/services.v1.PositionService/PositionCreate"
	PositionService_PositionGet_FullMethodName    = "/services.v1.PositionService/PositionGet"
)

// PositionServiceClient is the client API for PositionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PositionServiceClient interface {
	PositionCreate(ctx context.Context, in *PositionCreateRequest, opts ...grpc.CallOption) (*PositionCreateReply, error)
	PositionGet(ctx context.Context, in *PositionGetRequest, opts ...grpc.CallOption) (*PositionGetReply, error)
}

type positionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPositionServiceClient(cc grpc.ClientConnInterface) PositionServiceClient {
	return &positionServiceClient{cc}
}

func (c *positionServiceClient) PositionCreate(ctx context.Context, in *PositionCreateRequest, opts ...grpc.CallOption) (*PositionCreateReply, error) {
	out := new(PositionCreateReply)
	err := c.cc.Invoke(ctx, PositionService_PositionCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) PositionGet(ctx context.Context, in *PositionGetRequest, opts ...grpc.CallOption) (*PositionGetReply, error) {
	out := new(PositionGetReply)
	err := c.cc.Invoke(ctx, PositionService_PositionGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PositionServiceServer is the server API for PositionService service.
// All implementations should embed UnimplementedPositionServiceServer
// for forward compatibility
type PositionServiceServer interface {
	PositionCreate(context.Context, *PositionCreateRequest) (*PositionCreateReply, error)
	PositionGet(context.Context, *PositionGetRequest) (*PositionGetReply, error)
}

// UnimplementedPositionServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPositionServiceServer struct {
}

func (UnimplementedPositionServiceServer) PositionCreate(context.Context, *PositionCreateRequest) (*PositionCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PositionCreate not implemented")
}
func (UnimplementedPositionServiceServer) PositionGet(context.Context, *PositionGetRequest) (*PositionGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PositionGet not implemented")
}

// UnsafePositionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PositionServiceServer will
// result in compilation errors.
type UnsafePositionServiceServer interface {
	mustEmbedUnimplementedPositionServiceServer()
}

func RegisterPositionServiceServer(s grpc.ServiceRegistrar, srv PositionServiceServer) {
	s.RegisterService(&PositionService_ServiceDesc, srv)
}

func _PositionService_PositionCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).PositionCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_PositionCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).PositionCreate(ctx, req.(*PositionCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_PositionGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).PositionGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_PositionGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).PositionGet(ctx, req.(*PositionGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PositionService_ServiceDesc is the grpc.ServiceDesc for PositionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PositionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.v1.PositionService",
	HandlerType: (*PositionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PositionCreate",
			Handler:    _PositionService_PositionCreate_Handler,
		},
		{
			MethodName: "PositionGet",
			Handler:    _PositionService_PositionGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/positions.proto",
}
