// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: services/v1/positions.proto

package v1

import (
	v1 "github.com/MediStatTech/auth-client/pb/go/models/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =====================
// PositionCreate
// =====================
type PositionCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Postion *v1.Position_Create `protobuf:"bytes,1,opt,name=postion,proto3" json:"postion,omitempty"`
}

func (x *PositionCreateRequest) Reset() {
	*x = PositionCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_positions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionCreateRequest) ProtoMessage() {}

func (x *PositionCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_positions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionCreateRequest.ProtoReflect.Descriptor instead.
func (*PositionCreateRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_positions_proto_rawDescGZIP(), []int{0}
}

func (x *PositionCreateRequest) GetPostion() *v1.Position_Create {
	if x != nil {
		return x.Postion
	}
	return nil
}

type PositionCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PositionCreateReply) Reset() {
	*x = PositionCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_positions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionCreateReply) ProtoMessage() {}

func (x *PositionCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_positions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionCreateReply.ProtoReflect.Descriptor instead.
func (*PositionCreateReply) Descriptor() ([]byte, []int) {
	return file_services_v1_positions_proto_rawDescGZIP(), []int{1}
}

// =====================
// PositionGet
// =====================
type PositionGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PositionGetRequest) Reset() {
	*x = PositionGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_positions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionGetRequest) ProtoMessage() {}

func (x *PositionGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_positions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionGetRequest.ProtoReflect.Descriptor instead.
func (*PositionGetRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_positions_proto_rawDescGZIP(), []int{2}
}

type PositionGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Positions []*v1.Position_Read `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
}

func (x *PositionGetReply) Reset() {
	*x = PositionGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_positions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionGetReply) ProtoMessage() {}

func (x *PositionGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_positions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionGetReply.ProtoReflect.Descriptor instead.
func (*PositionGetReply) Descriptor() ([]byte, []int) {
	return file_services_v1_positions_proto_rawDescGZIP(), []int{3}
}

func (x *PositionGetReply) GetPositions() []*v1.Position_Read {
	if x != nil {
		return x.Positions
	}
	return nil
}

var File_services_v1_positions_proto protoreflect.FileDescriptor

var file_services_v1_positions_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34,
	0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x07, 0x70, 0x6f, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x4a, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xb8, 0x01,
	0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x56, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x0b, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x12, 0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x65, 0x64, 0x69, 0x53, 0x74, 0x61, 0x74, 0x54,
	0x65, 0x63, 0x68, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f,
	0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_v1_positions_proto_rawDescOnce sync.Once
	file_services_v1_positions_proto_rawDescData = file_services_v1_positions_proto_rawDesc
)

func file_services_v1_positions_proto_rawDescGZIP() []byte {
	file_services_v1_positions_proto_rawDescOnce.Do(func() {
		file_services_v1_positions_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_v1_positions_proto_rawDescData)
	})
	return file_services_v1_positions_proto_rawDescData
}

var file_services_v1_positions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_v1_positions_proto_goTypes = []interface{}{
	(*PositionCreateRequest)(nil), // 0: services.v1.PositionCreateRequest
	(*PositionCreateReply)(nil),   // 1: services.v1.PositionCreateReply
	(*PositionGetRequest)(nil),    // 2: services.v1.PositionGetRequest
	(*PositionGetReply)(nil),      // 3: services.v1.PositionGetReply
	(*v1.Position_Create)(nil),    // 4: models.v1.Position.Create
	(*v1.Position_Read)(nil),      // 5: models.v1.Position.Read
}
var file_services_v1_positions_proto_depIdxs = []int32{
	4, // 0: services.v1.PositionCreateRequest.postion:type_name -> models.v1.Position.Create
	5, // 1: services.v1.PositionGetReply.positions:type_name -> models.v1.Position.Read
	0, // 2: services.v1.PositionService.PositionCreate:input_type -> services.v1.PositionCreateRequest
	2, // 3: services.v1.PositionService.PositionGet:input_type -> services.v1.PositionGetRequest
	1, // 4: services.v1.PositionService.PositionCreate:output_type -> services.v1.PositionCreateReply
	3, // 5: services.v1.PositionService.PositionGet:output_type -> services.v1.PositionGetReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_v1_positions_proto_init() }
func file_services_v1_positions_proto_init() {
	if File_services_v1_positions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_v1_positions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_positions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_positions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_positions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_v1_positions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_positions_proto_goTypes,
		DependencyIndexes: file_services_v1_positions_proto_depIdxs,
		MessageInfos:      file_services_v1_positions_proto_msgTypes,
	}.Build()
	File_services_v1_positions_proto = out.File
	file_services_v1_positions_proto_rawDesc = nil
	file_services_v1_positions_proto_goTypes = nil
	file_services_v1_positions_proto_depIdxs = nil
}
