// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/v1/staffs.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StaffsService_CreateStaff_FullMethodName     = "/services.v1.StaffsService/CreateStaff"
	StaffsService_DeactivateStaff_FullMethodName = "/services.v1.StaffsService/DeactivateStaff"
	StaffsService_SignIn_FullMethodName          = "/services.v1.StaffsService/SignIn"
	StaffsService_FindStaff_FullMethodName       = "/services.v1.StaffsService/FindStaff"
	StaffsService_ListStaffs_FullMethodName      = "/services.v1.StaffsService/ListStaffs"
)

// StaffsServiceClient is the client API for StaffsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StaffsServiceClient interface {
	CreateStaff(ctx context.Context, in *CreateStaffRequest, opts ...grpc.CallOption) (*CreateStaffReply, error)
	DeactivateStaff(ctx context.Context, in *DeactivateStaffRequest, opts ...grpc.CallOption) (*DeactivateStaffReply, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInReply, error)
	FindStaff(ctx context.Context, in *FindStaffRequest, opts ...grpc.CallOption) (*FindStaffReply, error)
	ListStaffs(ctx context.Context, in *ListStaffsRequest, opts ...grpc.CallOption) (*ListStaffsReply, error)
}

type staffsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStaffsServiceClient(cc grpc.ClientConnInterface) StaffsServiceClient {
	return &staffsServiceClient{cc}
}

func (c *staffsServiceClient) CreateStaff(ctx context.Context, in *CreateStaffRequest, opts ...grpc.CallOption) (*CreateStaffReply, error) {
	out := new(CreateStaffReply)
	err := c.cc.Invoke(ctx, StaffsService_CreateStaff_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffsServiceClient) DeactivateStaff(ctx context.Context, in *DeactivateStaffRequest, opts ...grpc.CallOption) (*DeactivateStaffReply, error) {
	out := new(DeactivateStaffReply)
	err := c.cc.Invoke(ctx, StaffsService_DeactivateStaff_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffsServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInReply, error) {
	out := new(SignInReply)
	err := c.cc.Invoke(ctx, StaffsService_SignIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffsServiceClient) FindStaff(ctx context.Context, in *FindStaffRequest, opts ...grpc.CallOption) (*FindStaffReply, error) {
	out := new(FindStaffReply)
	err := c.cc.Invoke(ctx, StaffsService_FindStaff_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffsServiceClient) ListStaffs(ctx context.Context, in *ListStaffsRequest, opts ...grpc.CallOption) (*ListStaffsReply, error) {
	out := new(ListStaffsReply)
	err := c.cc.Invoke(ctx, StaffsService_ListStaffs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaffsServiceServer is the server API for StaffsService service.
// All implementations should embed UnimplementedStaffsServiceServer
// for forward compatibility
type StaffsServiceServer interface {
	CreateStaff(context.Context, *CreateStaffRequest) (*CreateStaffReply, error)
	DeactivateStaff(context.Context, *DeactivateStaffRequest) (*DeactivateStaffReply, error)
	SignIn(context.Context, *SignInRequest) (*SignInReply, error)
	FindStaff(context.Context, *FindStaffRequest) (*FindStaffReply, error)
	ListStaffs(context.Context, *ListStaffsRequest) (*ListStaffsReply, error)
}

// UnimplementedStaffsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedStaffsServiceServer struct {
}

func (UnimplementedStaffsServiceServer) CreateStaff(context.Context, *CreateStaffRequest) (*CreateStaffReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStaff not implemented")
}
func (UnimplementedStaffsServiceServer) DeactivateStaff(context.Context, *DeactivateStaffRequest) (*DeactivateStaffReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateStaff not implemented")
}
func (UnimplementedStaffsServiceServer) SignIn(context.Context, *SignInRequest) (*SignInReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedStaffsServiceServer) FindStaff(context.Context, *FindStaffRequest) (*FindStaffReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindStaff not implemented")
}
func (UnimplementedStaffsServiceServer) ListStaffs(context.Context, *ListStaffsRequest) (*ListStaffsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStaffs not implemented")
}

// UnsafeStaffsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StaffsServiceServer will
// result in compilation errors.
type UnsafeStaffsServiceServer interface {
	mustEmbedUnimplementedStaffsServiceServer()
}

func RegisterStaffsServiceServer(s grpc.ServiceRegistrar, srv StaffsServiceServer) {
	s.RegisterService(&StaffsService_ServiceDesc, srv)
}

func _StaffsService_CreateStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffsServiceServer).CreateStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffsService_CreateStaff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffsServiceServer).CreateStaff(ctx, req.(*CreateStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffsService_DeactivateStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffsServiceServer).DeactivateStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffsService_DeactivateStaff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffsServiceServer).DeactivateStaff(ctx, req.(*DeactivateStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffsService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffsServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffsService_SignIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffsServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffsService_FindStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffsServiceServer).FindStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffsService_FindStaff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffsServiceServer).FindStaff(ctx, req.(*FindStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffsService_ListStaffs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStaffsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffsServiceServer).ListStaffs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffsService_ListStaffs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffsServiceServer).ListStaffs(ctx, req.(*ListStaffsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StaffsService_ServiceDesc is the grpc.ServiceDesc for StaffsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StaffsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.v1.StaffsService",
	HandlerType: (*StaffsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStaff",
			Handler:    _StaffsService_CreateStaff_Handler,
		},
		{
			MethodName: "DeactivateStaff",
			Handler:    _StaffsService_DeactivateStaff_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _StaffsService_SignIn_Handler,
		},
		{
			MethodName: "FindStaff",
			Handler:    _StaffsService_FindStaff_Handler,
		},
		{
			MethodName: "ListStaffs",
			Handler:    _StaffsService_ListStaffs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/staffs.proto",
}
