// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: services/v1/staffs.proto

package v1

import (
	v1 "github.com/MediStatTech/auth-client/pb/go/models/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =====================
// StaffCreate
// =====================
type StaffCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Staff *v1.Staff_Create `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
}

func (x *StaffCreateRequest) Reset() {
	*x = StaffCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staffs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffCreateRequest) ProtoMessage() {}

func (x *StaffCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staffs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffCreateRequest.ProtoReflect.Descriptor instead.
func (*StaffCreateRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_staffs_proto_rawDescGZIP(), []int{0}
}

func (x *StaffCreateRequest) GetStaff() *v1.Staff_Create {
	if x != nil {
		return x.Staff
	}
	return nil
}

type StaffCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StaffCreateReply) Reset() {
	*x = StaffCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staffs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffCreateReply) ProtoMessage() {}

func (x *StaffCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staffs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffCreateReply.ProtoReflect.Descriptor instead.
func (*StaffCreateReply) Descriptor() ([]byte, []int) {
	return file_services_v1_staffs_proto_rawDescGZIP(), []int{1}
}

// =====================
// StaffDeactivate
// =====================
type StaffDeactivateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StaffId string `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
}

func (x *StaffDeactivateRequest) Reset() {
	*x = StaffDeactivateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staffs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffDeactivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffDeactivateRequest) ProtoMessage() {}

func (x *StaffDeactivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staffs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffDeactivateRequest.ProtoReflect.Descriptor instead.
func (*StaffDeactivateRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_staffs_proto_rawDescGZIP(), []int{2}
}

func (x *StaffDeactivateRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type StaffDeactivateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StaffDeactivateReply) Reset() {
	*x = StaffDeactivateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staffs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffDeactivateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffDeactivateReply) ProtoMessage() {}

func (x *StaffDeactivateReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staffs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffDeactivateReply.ProtoReflect.Descriptor instead.
func (*StaffDeactivateReply) Descriptor() ([]byte, []int) {
	return file_services_v1_staffs_proto_rawDescGZIP(), []int{3}
}

// =====================
// SignIn
// =====================
type SignInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staffs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staffs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_staffs_proto_rawDescGZIP(), []int{4}
}

func (x *SignInRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SignInReply) Reset() {
	*x = SignInReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staffs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInReply) ProtoMessage() {}

func (x *SignInReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staffs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInReply.ProtoReflect.Descriptor instead.
func (*SignInReply) Descriptor() ([]byte, []int) {
	return file_services_v1_staffs_proto_rawDescGZIP(), []int{5}
}

func (x *SignInReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// =====================
// StaffRetrieve
// =====================
type StaffRetrieveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StaffId string `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
}

func (x *StaffRetrieveRequest) Reset() {
	*x = StaffRetrieveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staffs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffRetrieveRequest) ProtoMessage() {}

func (x *StaffRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staffs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffRetrieveRequest.ProtoReflect.Descriptor instead.
func (*StaffRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_staffs_proto_rawDescGZIP(), []int{6}
}

func (x *StaffRetrieveRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type StaffRetrieveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Staff *v1.Staff_Read `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
}

func (x *StaffRetrieveReply) Reset() {
	*x = StaffRetrieveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staffs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffRetrieveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffRetrieveReply) ProtoMessage() {}

func (x *StaffRetrieveReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staffs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffRetrieveReply.ProtoReflect.Descriptor instead.
func (*StaffRetrieveReply) Descriptor() ([]byte, []int) {
	return file_services_v1_staffs_proto_rawDescGZIP(), []int{7}
}

func (x *StaffRetrieveReply) GetStaff() *v1.Staff_Read {
	if x != nil {
		return x.Staff
	}
	return nil
}

// =====================
// StaffGet
// =====================
type StaffGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StaffGetRequest) Reset() {
	*x = StaffGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staffs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffGetRequest) ProtoMessage() {}

func (x *StaffGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staffs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffGetRequest.ProtoReflect.Descriptor instead.
func (*StaffGetRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_staffs_proto_rawDescGZIP(), []int{8}
}

type StaffGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Staffs []*v1.Staff_Read `protobuf:"bytes,1,rep,name=staffs,proto3" json:"staffs,omitempty"`
}

func (x *StaffGetReply) Reset() {
	*x = StaffGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_staffs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffGetReply) ProtoMessage() {}

func (x *StaffGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_staffs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffGetReply.ProtoReflect.Descriptor instead.
func (*StaffGetReply) Descriptor() ([]byte, []int) {
	return file_services_v1_staffs_proto_rawDescGZIP(), []int{9}
}

func (x *StaffGetReply) GetStaffs() []*v1.Staff_Read {
	if x != nil {
		return x.Staffs
	}
	return nil
}

var File_services_v1_staffs_proto protoreflect.FileDescriptor

var file_services_v1_staffs_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74,
	0x61, 0x66, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x66, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x43, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x66, 0x66, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x33, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64, 0x22, 0x16, 0x0a,
	0x14, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x41, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x23, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e,
	0x49, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x31, 0x0a,
	0x14, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64,
	0x22, 0x41, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x66, 0x66, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x66, 0x66, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x66, 0x66, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x66, 0x66, 0x73, 0x32, 0x94, 0x03, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x66, 0x66,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x59, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x66, 0x66,
	0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x1a, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x12, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x66, 0x66,
	0x47, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x37, 0x5a,
	0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x65, 0x64, 0x69,
	0x53, 0x74, 0x61, 0x74, 0x54, 0x65, 0x63, 0x68, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2d, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_v1_staffs_proto_rawDescOnce sync.Once
	file_services_v1_staffs_proto_rawDescData = file_services_v1_staffs_proto_rawDesc
)

func file_services_v1_staffs_proto_rawDescGZIP() []byte {
	file_services_v1_staffs_proto_rawDescOnce.Do(func() {
		file_services_v1_staffs_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_v1_staffs_proto_rawDescData)
	})
	return file_services_v1_staffs_proto_rawDescData
}

var file_services_v1_staffs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_services_v1_staffs_proto_goTypes = []interface{}{
	(*StaffCreateRequest)(nil),     // 0: services.v1.StaffCreateRequest
	(*StaffCreateReply)(nil),       // 1: services.v1.StaffCreateReply
	(*StaffDeactivateRequest)(nil), // 2: services.v1.StaffDeactivateRequest
	(*StaffDeactivateReply)(nil),   // 3: services.v1.StaffDeactivateReply
	(*SignInRequest)(nil),          // 4: services.v1.SignInRequest
	(*SignInReply)(nil),            // 5: services.v1.SignInReply
	(*StaffRetrieveRequest)(nil),   // 6: services.v1.StaffRetrieveRequest
	(*StaffRetrieveReply)(nil),     // 7: services.v1.StaffRetrieveReply
	(*StaffGetRequest)(nil),        // 8: services.v1.StaffGetRequest
	(*StaffGetReply)(nil),          // 9: services.v1.StaffGetReply
	(*v1.Staff_Create)(nil),        // 10: models.v1.Staff.Create
	(*v1.Staff_Read)(nil),          // 11: models.v1.Staff.Read
}
var file_services_v1_staffs_proto_depIdxs = []int32{
	10, // 0: services.v1.StaffCreateRequest.staff:type_name -> models.v1.Staff.Create
	11, // 1: services.v1.StaffRetrieveReply.staff:type_name -> models.v1.Staff.Read
	11, // 2: services.v1.StaffGetReply.staffs:type_name -> models.v1.Staff.Read
	0,  // 3: services.v1.StaffsService.StaffCreate:input_type -> services.v1.StaffCreateRequest
	2,  // 4: services.v1.StaffsService.StaffDeactivate:input_type -> services.v1.StaffDeactivateRequest
	4,  // 5: services.v1.StaffsService.SignIn:input_type -> services.v1.SignInRequest
	6,  // 6: services.v1.StaffsService.StaffRetrieve:input_type -> services.v1.StaffRetrieveRequest
	8,  // 7: services.v1.StaffsService.StaffGet:input_type -> services.v1.StaffGetRequest
	1,  // 8: services.v1.StaffsService.StaffCreate:output_type -> services.v1.StaffCreateReply
	3,  // 9: services.v1.StaffsService.StaffDeactivate:output_type -> services.v1.StaffDeactivateReply
	5,  // 10: services.v1.StaffsService.SignIn:output_type -> services.v1.SignInReply
	7,  // 11: services.v1.StaffsService.StaffRetrieve:output_type -> services.v1.StaffRetrieveReply
	9,  // 12: services.v1.StaffsService.StaffGet:output_type -> services.v1.StaffGetReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_services_v1_staffs_proto_init() }
func file_services_v1_staffs_proto_init() {
	if File_services_v1_staffs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_v1_staffs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_staffs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_staffs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffDeactivateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_staffs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffDeactivateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_staffs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_staffs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_staffs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffRetrieveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_staffs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffRetrieveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_staffs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_staffs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_v1_staffs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_staffs_proto_goTypes,
		DependencyIndexes: file_services_v1_staffs_proto_depIdxs,
		MessageInfos:      file_services_v1_staffs_proto_msgTypes,
	}.Build()
	File_services_v1_staffs_proto = out.File
	file_services_v1_staffs_proto_rawDesc = nil
	file_services_v1_staffs_proto_goTypes = nil
	file_services_v1_staffs_proto_depIdxs = nil
}
