// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/v1/staffs.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StaffsService_StaffCreate_FullMethodName     = "/services.v1.StaffsService/StaffCreate"
	StaffsService_StaffDeactivate_FullMethodName = "/services.v1.StaffsService/StaffDeactivate"
	StaffsService_SignIn_FullMethodName          = "/services.v1.StaffsService/SignIn"
	StaffsService_StaffRetrieve_FullMethodName   = "/services.v1.StaffsService/StaffRetrieve"
	StaffsService_StaffGet_FullMethodName        = "/services.v1.StaffsService/StaffGet"
)

// StaffsServiceClient is the client API for StaffsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StaffsServiceClient interface {
	StaffCreate(ctx context.Context, in *StaffCreateRequest, opts ...grpc.CallOption) (*StaffCreateReply, error)
	StaffDeactivate(ctx context.Context, in *StaffDeactivateRequest, opts ...grpc.CallOption) (*StaffDeactivateReply, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInReply, error)
	StaffRetrieve(ctx context.Context, in *StaffRetrieveRequest, opts ...grpc.CallOption) (*StaffRetrieveReply, error)
	StaffGet(ctx context.Context, in *StaffGetRequest, opts ...grpc.CallOption) (*StaffGetReply, error)
}

type staffsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStaffsServiceClient(cc grpc.ClientConnInterface) StaffsServiceClient {
	return &staffsServiceClient{cc}
}

func (c *staffsServiceClient) StaffCreate(ctx context.Context, in *StaffCreateRequest, opts ...grpc.CallOption) (*StaffCreateReply, error) {
	out := new(StaffCreateReply)
	err := c.cc.Invoke(ctx, StaffsService_StaffCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffsServiceClient) StaffDeactivate(ctx context.Context, in *StaffDeactivateRequest, opts ...grpc.CallOption) (*StaffDeactivateReply, error) {
	out := new(StaffDeactivateReply)
	err := c.cc.Invoke(ctx, StaffsService_StaffDeactivate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffsServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInReply, error) {
	out := new(SignInReply)
	err := c.cc.Invoke(ctx, StaffsService_SignIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffsServiceClient) StaffRetrieve(ctx context.Context, in *StaffRetrieveRequest, opts ...grpc.CallOption) (*StaffRetrieveReply, error) {
	out := new(StaffRetrieveReply)
	err := c.cc.Invoke(ctx, StaffsService_StaffRetrieve_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffsServiceClient) StaffGet(ctx context.Context, in *StaffGetRequest, opts ...grpc.CallOption) (*StaffGetReply, error) {
	out := new(StaffGetReply)
	err := c.cc.Invoke(ctx, StaffsService_StaffGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaffsServiceServer is the server API for StaffsService service.
// All implementations should embed UnimplementedStaffsServiceServer
// for forward compatibility
type StaffsServiceServer interface {
	StaffCreate(context.Context, *StaffCreateRequest) (*StaffCreateReply, error)
	StaffDeactivate(context.Context, *StaffDeactivateRequest) (*StaffDeactivateReply, error)
	SignIn(context.Context, *SignInRequest) (*SignInReply, error)
	StaffRetrieve(context.Context, *StaffRetrieveRequest) (*StaffRetrieveReply, error)
	StaffGet(context.Context, *StaffGetRequest) (*StaffGetReply, error)
}

// UnimplementedStaffsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedStaffsServiceServer struct {
}

func (UnimplementedStaffsServiceServer) StaffCreate(context.Context, *StaffCreateRequest) (*StaffCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffCreate not implemented")
}
func (UnimplementedStaffsServiceServer) StaffDeactivate(context.Context, *StaffDeactivateRequest) (*StaffDeactivateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffDeactivate not implemented")
}
func (UnimplementedStaffsServiceServer) SignIn(context.Context, *SignInRequest) (*SignInReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedStaffsServiceServer) StaffRetrieve(context.Context, *StaffRetrieveRequest) (*StaffRetrieveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffRetrieve not implemented")
}
func (UnimplementedStaffsServiceServer) StaffGet(context.Context, *StaffGetRequest) (*StaffGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffGet not implemented")
}

// UnsafeStaffsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StaffsServiceServer will
// result in compilation errors.
type UnsafeStaffsServiceServer interface {
	mustEmbedUnimplementedStaffsServiceServer()
}

func RegisterStaffsServiceServer(s grpc.ServiceRegistrar, srv StaffsServiceServer) {
	s.RegisterService(&StaffsService_ServiceDesc, srv)
}

func _StaffsService_StaffCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffsServiceServer).StaffCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffsService_StaffCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffsServiceServer).StaffCreate(ctx, req.(*StaffCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffsService_StaffDeactivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffDeactivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffsServiceServer).StaffDeactivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffsService_StaffDeactivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffsServiceServer).StaffDeactivate(ctx, req.(*StaffDeactivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffsService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffsServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffsService_SignIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffsServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffsService_StaffRetrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffRetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffsServiceServer).StaffRetrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffsService_StaffRetrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffsServiceServer).StaffRetrieve(ctx, req.(*StaffRetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffsService_StaffGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffsServiceServer).StaffGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffsService_StaffGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffsServiceServer).StaffGet(ctx, req.(*StaffGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StaffsService_ServiceDesc is the grpc.ServiceDesc for StaffsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StaffsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.v1.StaffsService",
	HandlerType: (*StaffsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StaffCreate",
			Handler:    _StaffsService_StaffCreate_Handler,
		},
		{
			MethodName: "StaffDeactivate",
			Handler:    _StaffsService_StaffDeactivate_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _StaffsService_SignIn_Handler,
		},
		{
			MethodName: "StaffRetrieve",
			Handler:    _StaffsService_StaffRetrieve_Handler,
		},
		{
			MethodName: "StaffGet",
			Handler:    _StaffsService_StaffGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/staffs.proto",
}
